# Generated by Django 5.2.1 on 2025-05-31 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usurios',
            new_name='Modelusurios',
        ),
    ]
