# Generated by Django 5.2.1 on 2025-06-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_model_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelusurios',
            name='iduser',
        ),
        migrations.AddField(
            model_name='modelusurios',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
